# Generated by Django 5.2 on 2025-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('overall_sentiment', models.CharField(max_length=20)),
                ('satisfaction_score', models.IntegerField()),
                ('reason_for_call', models.TextField()),
                ('sentence_sentiments', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
